language: python
python:
    - "3.6"
install:
    - pip install pytest pytest-cov
    - pip install codecov
    - pip install -r requirements.txt
    - pip install .
script:
    - pytest --cov=adlib27/
after_success:
    - codecov
